# Generated by Django 3.1.13 on 2022-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alum',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='alumni.Achievement'),
        ),
    ]
