# Generated by Django 3.1.13 on 2021-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='A project I made at Merit Academy.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('REPL', 'Repl Console App'), ('WEBGL_GAME', 'WebGL Game'), ('WEBSITE', 'Website')], default='R', max_length=20),
        ),
    ]
