# Generated by Django 3.1.13 on 2021-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211208_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('GOOGLE_SITE', 'Google Site'), ('REPL', 'Repl Console App'), ('WEB_APP', 'Web App'), ('WEBGL_GAME', 'WebGL Game'), ('WEBSITE', 'Website')], default='REPL', max_length=20),
        ),
    ]
