# Generated by Django 3.1.13 on 2022-01-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='countsFor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.AddField(
            model_name='course',
            name='dstudies',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fullyear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='science',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
