# Generated by Django 3.1.13 on 2022-01-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220120_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('GEN', 'Explorer General'), ('SPE', 'Explorer Specific'), ('COM', 'Completer')], default='GEN', max_length=10),
            preserve_default=False,
        ),
    ]
